### ISSUE TITLE
Dynamic import of shikiji adds 1.2Mb to gzipped bundle

### ISSUE THREAD

**Issue by dpeek** [shellscape/jsx-email#183]
Hi there! I'm using jsx-email in a serverless context (Cloudflare Workers) and noticed my bundle size jumped quite a bit after adding jsx-email. After some investigation it seems that the `Code` component importing shikiji is the main culprit, adding almost 8MB of uncompressed (1.2Mb gzipped) javascript to the bundle.

This isn't a blocker as I'm still below the worker size limit (although above what they recommend). Still, it seems like it would be nice to allow users to opt-out of this dependency (it's unlikely we'll need code highlighting in our emails!)

I've tried importing components individually, but I guess since renderer references them all it's impossible for them to be tree-shaken? Perhaps you could change the API so that users can pass in a highlighting function to the renderer?

**Comment by shellscape** [comment]
@dpeek shiki has had a lot of work done lately, and we're going to be updating to the latest version in v2.0.0 (https://github.com/shellscape/jsx-email/pull/206). I've also pinged @antfu on X to see if there are any additional strategies that would make sense to reduce the bundling size. going to close this one for now, since there's nothing really actionable on our end at the moment.
