### ISSUE TITLE
Incompatible with React Router 7 apps

### ISSUE THREAD

**Issue by tobimori** [shellscape/jsx-email#246]
When installing jsx-email in a RR7 app, there are numerous errors that seem to be fixed when removing jsx-email:

![image](https://github.com/user-attachments/assets/4f578917-6fa2-4a16-b9ef-0e9feaba89f6)

**Comment by shellscape** [comment]
If you'd like to report a proper issue, we'd welcome it. You're probably better off reporting this to the react-router project as this is more likely an upstream problem with react-router. Here's a direct link: https://github.com/remix-run/react-router/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=%5BBug%5D%3A+

**Comment by tobimori** [comment]
It's not an upstream issue, the incompatibility is in jsx-email because there are mismatching dependency versions installed.

**Comment by tobimori** [comment]
Also, which issue template? I didn't see one when creating a new issue?

**Comment by shellscape** [comment]
I'm a bit confused - based on your github profile this should not be new to you:

<img width="885" alt="Screenshot 2024-11-23 at 10 40 27 AM" src="https://github.com/user-attachments/assets/ee8c8bb5-9151-46b7-afa2-3a0b0d20c112">
<img width="642" alt="Screenshot 2024-11-23 at 10 40 32 AM" src="https://github.com/user-attachments/assets/a01081d7-635d-4b83-9ba0-113d5610effd">

If you'd like to open a new issue and follow our template, you're welcome to. Since this is nuanced to your environment, your reproduction should include the conditions that led to your error, as well as details about any information you gleaned during your triage. Worth noting that generic statements like "there are mismatching dependency versions installed" isn't very helpful, but actual details are helpful.

**Comment by tobimori** [comment]
I sent a video on Discord, I don't see this. I'd have certainly not ignored it!

Here's the reproduction repo: https://github.com/tobimori/jsx-email-repro
